name = "research-market-signups"
main = "src/index.js"
compatibility_date = "2026-05-04"

[[d1_databases]]
binding = "DB"
database_name = "research_market_signups"
database_id = "41479d41-295e-4ccb-84ba-88f4435750fd"
